OSC/bc_osc_jupyter

- CHANGELOG.md
- README.md
- form.yml
- manifest.yml
- template/after.sh
- template/script.sh.erb
Fixes #14
Fixes #15
Fixes #16
Fixes #17
> Fix formatting issues throughout code

- template/script.sh.erb
Adding support for a Julia 1.0 kernel.
> Initial commit supporting a Julia 1.0 kernel

- form.yml
- template/before.sh.erb
- template/script.sh.erb
- view.html.erb
We have updated versions for jupyterlab as well as a Safari bug fix
> Choose versions

- form.yml
- template/before.sh.erb
- template/script.sh.erb
add classroom flag to support classroom deployments with limited environments (so we don't load _any_ other kernels) and the ability to load a jupyter notebook directly into a ipynb file.
> add classroom flag

- template/before.sh.erb
classroom directories to set facls so instructors can copy hw files
> classroom directories to set facls so instructors can copy hw files

- submit.yml.erb
> bugfixes for v0.16.0

- form.yml
- submit.yml.erb
support owens-slurm cluster by toggling on the adapter type
> support owens-slurm cluster by toggling on the adapter type

- form.yml.erb
- submit.yml.erb
mv account to a select widget with only valid groups as options
> mv account to a select widget with only valid groups as options

- CHANGELOG.md
> update changelog for v0.20.0

- CHANGELOG.md
- form.yml.erb
update jupyter versions for security fixes, dropping 0.35.
> update jupyter versions for security fixes, dropping 0.35.

- CHANGELOG.md
> update changelog for v0.20.1

- CHANGELOG.md
- form.js
update hide & show logic to default show and only hide explicitly told so
> update hide & show logic

- submit.yml.erb
Requires https://github.com/OSC/ood_core/pull/317
> Set cluster label for Kubernetes

- submit.yml.erb
DO NOT MERGE until we know if this solution is needed, just showing as how to run on any node.
> Run on any Kubernetes node

- form.yml.erb
- template/before.sh.erb
- template/script.sh.erb
Changed Jupyter Notebook/Lab from checkbook to radio button.
> Gerald radio button 81

- form.yml.erb
- template/script.sh.erb
Add CUDA 11 modules and fix
1. mode radio options
2. no cuda module loaded in template/scritp.sh.erb
> Update cuda modules and fix two bugs

- form.yml.erb
> fix a mistype

- info.md.erb
add info card about all the updates that have happened since the downtime.
> add info card

- CHANGELOG.md
- view.html.erb
> 3.0 compliant url encode

- info.md.erb
> Removing updates since downtime message.

- form.yml.erb
rm c18 options for the downtime on the 13th.
> rm c18 options

- form.yml.erb
Reverts OSC/bc_osc_jupyter#105
> Add c18 options back in.

- form.yml
> fix cardinal min/max cores

- form.yml
- submit.yml.erb
> add ability to specify gpus

- form.yml
> support for nextgen ascend

- form.yml
correct max cores for next gen ascend
> correct max cores for next gen ascend

- form.yml
Remove next-generation Ascend as it's merging into ascend on Monday.
> remove NGA

- template/before.sh.erb
- template/script.sh.erb
> allow for notebook

- .gitlab-ci.yml
- template/script.sh.erb
support for el9 and remove xalt
> support for el9 and remove xalt

- form.yml
- template/script.sh.erb
fix k8s by hard coding versions as kubernetes cannot correctly respond to `auto_modules_app_jupyter`.
> fix k8s by hard coding versions

- form.yml
remove pitzer-rhel9 for migration into pitzer
> remove pitzer-rhel9 for migration into pitzer
